{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "evermount-capital.fullname" . }}
  labels:
    {{- include "evermount-capital.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "evermount-capital.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
